version: '2'

networks:
  prodnetwork:
    driver: bridge

services:

 rails-ide:
  image: mercuriete/docker-cloud9-ruby-rails
  ports:
    - "80:80"
    - "8080:8080"
  networks:
    - prodnetwork
  depends_on:
    - selhub



 selhub:
  image: selenium/hub
  ports:
    - 4444:4444
  networks:
    - prodnetwork

 nodeff:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  networks:
    - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selhub
  depends_on:
    - selhub

 nodechrome:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  networks:
    - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selhub
  depends_on:
    - selhub

 nodeie:
  image: mercuriete/node-ie8-debug
  ports:
    - 5900
    - 5555:5555
  networks:
    - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selhub
  depends_on:
    - selhub
